### ISSUE TITLE
AttributeError while executing the Mod2Bac.py

### ISSUE THREAD

**Issue by sburdka** [anthonydlanza/Mod2Bac#2]
Dear  @anthonydlanza
I have tried to execute Mod2Bac.Py file. But following error is coming. could you able to guide what is the cause of it.
or any fix for this issue. 

`
D:\BACnet\Mod2Bac>python3.7` Mod2Bac.py
Traceback (most recent call last):
  File "Mod2Bac.py", line 10, in <module>
    import test
  File "D:\BACnet\Mod2Bac\test.py", line 12, in <module>
    for i in ip.keys():
AttributeError: 'str' object has no attribute `'keys`
`
                                  
IS it not supporting Windows OS? Following Output coming from shell

>>> getnic.ipaddr(interfaces)
'Linux OS is currently supported, Check OS'

**Comment by anthonydlanza** [comment]
Hello, 

This only provides support for Linux -- Specifically, Raspberry Pi.
